version: "3.9"
services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_android
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  web:
    build: ./php
    depends_on:
      - db
    volumes:
      - ./php/html:/var/www/html
    ports:
      - "8080:80"
    environment:
      PHP_DISPLAY_ERRORS: 1

volumes:
  db_data:
